---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudChaps EC2 instances stack - Backend (MySQL client)

Parameters:
  AMIID:
    Type: AWS::EC2::Image::Id
    Default: ami-0ec10929233384c7f

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: cloudchaps_resorts_keypair

  Env:
    Description: Please enter the environment name
    Type: String
    Default: Development

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  DBUserName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CloudChaps_DEV_dbUserName
    Description: DB User Name stored in SSM
  
  DBMasterPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CloudChaps_DEV_dbUserPassword
    Description: DB Password stored in SSM

Resources:
  ccBackendServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIID
      SubnetId:
        Fn::ImportValue: DEV01VPCManagement-PrivateSubnet
      SecurityGroupIds:
        - Fn::ImportValue: DEV02SecurityGroupsManagement-ccDBSecurityGroup
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Backend-Server"
        - Key: Project
          Value: CloudChaps_Hotels
        - Key: Environment
          Value: !Ref Env
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt update -y
            apt-get install -y mysql-server net-tools
            # 1. Allow remote connections
            sed -i 's/bind-address.*=.*127.0.0.1/bind-address            = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
            # 2. Restart MySQL
            systemctl restart mysql
            # 3. Create DB, user and grant privileges
            mysql -u root <<EOF
            CREATE DATABASE IF NOT EXISTS cloudchaps_hotels;
            CREATE USER IF NOT EXISTS 'db_admin'@'%' IDENTIFIED BY 'DB_PASSWORD';
            GRANT ALL PRIVILEGES ON cloudchaps_hotels.* TO 'db_admin'@'%';
            FLUSH PRIVILEGES;
            EOF

Outputs:
  BackendPrivateIP:
    Description: Backend EC2 private IP
    Value: !GetAtt ccBackendServer.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-BackendPrivateIP