---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudChaps EC2 instances stack Frontend target SecurityGroupIds

Parameters:
  TargetGroupName:
    Description: Please enter the target group name
    Type: String
    Default: CloudChapsTG

  LoadBalancerName:
    Description: Please enter the Load Balancer name
    Type: String
    Default: CloudChapsALB
  
  WEBServerPrivateIP1:
    Type: String
    Default: 10.0.2.100
    Description: Please enter frontend Server Private IP - 1
  
  WEBServerPrivateIP2:
    Type: String
    Default: 10.0.2.100
    Description: Please enter frontend Server Private IP - 2
  
  WEBServerPrivateIP3:
    Type: String
    Default: 10.0.2.100
    Description: Please enter frontend Server Private IP - 3

Resources:

  ccFrontEndTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      Protocol: TCP
      Port: 80
      TargetType: ip
      VpcId: 
        Fn::ImportValue: DEV01VPCManagement-MainVPC
      Targets:
        - Id: !Ref WEBServerPrivateIP1
          Port: 8080
        - Id: !Ref WEBServerPrivateIP2
          Port: 8080
        - Id: !Ref WEBServerPrivateIP3
          Port: 8080
  
  ccLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Type: application
      Scheme: internet-facing  # or internal if truly private
      Subnets: 
        - Fn::ImportValue: DEV01VPCManagement-PublicSubnet
      SecurityGroups: 
        - Fn::ImportValue: DEV02SecurityGroupsManagement-ccWebServerSecurityGroup

  ccListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ccLoadBalancer
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ccFrontEndTargetGroup