---
name: Build AWS infrastucture via cloud Formation
on:
  push:
    branches: [ main ]
  
  paths:
    - '02_CreateEC2Instances.yaml'
    - '99_CloudFormation/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest commit from repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy EC2 Instances
      run: aws cloudformation deploy \ 
        --template-file 99_CloudFormation/02_CreateEC2Instances.yaml \
        --stack-name DEV01EC2Instances \
        --role-arn ${{ secrets.DEV_ROLE_ARN }}
