---
name: Build AWS infrastucture via cloud Formation
on:
  push:
    branches: [ development ]
  
    paths:
      - '99_CloudFormation/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest commit from repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy VPC, Internet Gateway and Route Table
      run: |
        aws cloudformation deploy \
          --template-file ./10_CloudFormation/01_CreateVPC.yaml \
          --stack-name DEV01VPCManagement \
          --role-arn ${{ secrets.DEV_ROLE_ARN }}
    
    - name: Deploy Security groups
      run: |
        aws cloudformation deploy \
          --template-file ./10_CloudFormation/02_CreateSecurityGroups.yaml \
          --stack-name DEV02SecurityGroupsManagement \
          --role-arn ${{ secrets.DEV_ROLE_ARN }}
