---
name: Build AWS infrastucture via cloud Formation
on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest commit from repo
      uses: actions/checkout@v
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21 
      uses: actions/setup-java@v4 
      with: 
        distribution: 'temurin' 
        java-version: '21'
    
    - name: cd into the application folder
      run: cd 01_Properties && ls -la
    
    - name: Build with Maven 
      run: mvn clean package -DskipTests=true
    - uses: actions/upload-artifact@v4
      with:
        name: app-war
        path: 01_Properties/target/*.war
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-war
        path: target
    
    - name: list files
      run: ls -la target && ls -la
    
    
  

